# Generated by Django 6.0 on 2026-02-19 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('habilidades_requeridas', models.JSONField(default=list)),
                ('certificacoes_requeridas', models.JSONField(default=list)),
                ('formacao_desejada', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='projetos.projeto')),
            ],
        ),
    ]
