# Generated by Django 6.0 on 2026-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vaga_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='senioridade',
            field=models.CharField(choices=[('estagio', 'Estágio'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista')], default='pleno', max_length=20),
        ),
    ]
