# Generated by Django 6.0 on 2026-03-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vaga_senioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='area',
            field=models.CharField(blank=True, choices=[('inovacao', 'Inovação'), ('tecnologia', 'Tecnologia'), ('dados', 'Dados'), ('design', 'Design'), ('produto', 'Produto'), ('negocios', 'Negócios'), ('marketing', 'Marketing'), ('operacoes', 'Operações')], max_length=20, null=True),
        ),
    ]
