# Generated by Django 6.0 on 2026-04-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_vaga_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='descricao',
        ),
    ]
