services:

  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - db_data:/app/data
      - media_data:/app/media
      - embeddings_cache:/app/recomendacao/ml_models/embeddings_cache
    ports:
      - "8000:8000"
    depends_on:
      - ai-service
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai-service:8001
    networks:
      - rh-net
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    container_name: ai-service
    volumes:
      - embeddings_cache:/app/embeddings_cache
    ports:
      - "8001:8001"
    env_file:
      - ./ai-service/.env
    networks:
      - rh-net
    restart: unless-stopped

volumes:
  embeddings_cache:
  db_data:
  media_data:

networks:
  rh-net:
    driver: bridge
