# Generated by Django 6.0 on 2026-02-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='status',
        ),
    ]
