# Generated by Django 6.0 on 2026-03-13 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0002_remove_candidatura_colaborador_candidatura_usuario'),
        ('vagas', '0002_vaga_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('usuario', 'vaga')},
        ),
    ]
