# Generated by Django 6.0 on 2026-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_alter_candidatura_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
