# Generated by Django 6.0 on 2026-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('produto_digital', 'Produto digital'), ('servico', 'Serviço'), ('pesquisa', 'Pesquisa'), ('outro', 'Outro')], default='produto_digital', max_length=30),
        ),
    ]
