# Generated by Django 6.0 on 2026-02-19 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(choices=[('DESENVOLVEDOR', 'Desenvolvedor'), ('DESIGNER', 'Designer'), ('QA', 'QA'), ('PM', 'Product Manager'), ('ANALISTA', 'Analista')], max_length=30)),
                ('senioridade', models.CharField(choices=[('ESTAGIO', 'Estágio'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('ESPECIALISTA', 'Especialista')], max_length=20)),
                ('area', models.CharField(choices=[('TI', 'Tecnologia da Informação'), ('RH', 'Recursos Humanos'), ('DESIGN', 'Design'), ('PRODUTO', 'Produto'), ('DADOS', 'Dados')], max_length=30)),
                ('habilidades', models.JSONField(default=list)),
                ('certificacoes', models.JSONField(default=list)),
                ('formacao', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
