# Generated by Django 6.0 on 2025-12-11 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('habilidades', models.JSONField(default=list)),
                ('certificacoes', models.JSONField(default=list)),
                ('formacao', models.CharField(blank=True, max_length=200, null=True)),
                ('tempo_empresa_meses', models.IntegerField(default=0)),
            ],
        ),
    ]
